### ISSUE TITLE
Can not find python module docsets

### ISSUE THREAD

**Issue by twsam03** [otsaloma/docsets#1]
There is no docsets module of python, can not find it via pip,.

**Comment by otsaloma** [comment]
It's not an external module. That

```python
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
```

basically imports the top level `__init__.py` file. The only reason I see that it wouldn't work is if you cloned the repo to a directory of some other name than "docsets". Maybe I should use `importlib` to get around this limitation, depends on whether the code gets more verbose or not.
